experiment:
  name: "Darcy Flow Generation"
  seed: 41 #42
  simulator_type: "DARCY"
  reduced_model_type: "FIM" # "FIM" or "RAND"
  output_dir: "datasets/dataset_DARCY2"

viz_settings:
  plot_interval: 1
  plot_vector_count: 5
  plots_dir: "datasets/dataset_DARCY/plots2"

data_settings:
  num_samples: 256
  num_workers: 1
  num_subsamples: 100
  data_dir: "datasets/dataset_DARCY/samples2"

simulator_settings:
  size: 128 # Grid size
  T: 500000

reduced_model_settings:
  probe_size: 1024 #10
  noise_std: 1.0
  eigen_value_fraction: 0.01
  eigen_vector_count: 128 # Overrides eigen_value_fraction if set
