base_config: ../ns_default.yaml

experiment:
  name: "n=64_m=FNO_l=L2"
  tags:
    - "64 samples"
    - "FNO"

model_settings:
  loss_type: "L2"
  learning_rate: 8e-4

training_settings:
  num_train: 64
  num_test: 8
  num_epoch: 100