base_config: ../ns_default.yaml

experiment:
  name: "n=64_e=4_m=FNO_s=RAND_l=JAC"
  tags:
    - "4 Eigenvectors"
    - "64 samples"
    - "FNO"
    - "RAND"
    - "JAC"

data_settings:
  sample_directories:
    - "/home/ubuntu/DeFINO/datasets/dataset_NS_rand_batch1"
    - "/home/ubuntu/DeFINO/datasets/dataset_NS_rand_batch2"
    - "/home/ubuntu/DeFINO/datasets/dataset_NS_rand_batch3"
    - "/home/ubuntu/DeFINO/datasets/dataset_NS_rand_batch4"

model_settings:
  loss_type: "JAC"
  learning_rate: 8e-4

training_settings:
  num_train: 64
  num_test: 8
  num_epoch: 100