base_config: ../ns_default.yaml

experiment:
  name: "n=128_e=8_m=FNO_s=RAND_l=JAC"
  tags:
    - "4 Eigenvectors"
    - "64 samples"
    - "FNO"
    - "RAND"
    - "JAC"

data_settings:
  sample_directories:
    - "../datasets/dataset_NS_rand_batch1"
    - "../datasets/dataset_NS_rand_batch2"
    - "../datasets/dataset_NS_rand_batch3"
    - "../datasets/dataset_NS_rand_batch4"

model_settings:
  loss_type: "JAC"
  learning_rate: 8e-4

training_settings:
  num_train: 128
  num_test: 16
  num_epoch: 150