base_config: ../ns_default.yaml

experiment:
  name: "n=64_e=4_m=FNO_s=RFS_l=JAC"
  tags:
    - "4 Eigenvectors"
    - "64 samples"
    - "FNO"
    - "RFS"
    - "JAC"

model_settings:
  loss_type: "JAC"
  train_eigen_count: 4

training_settings:
  num_samples: 64
