base_config: ../ns_default.yaml

experiment:
  name: "n=128_e=4_m=FNO_s=RFS_l=JAC"
  tags:
    - "4 Eigenvectors"
    - "128 samples"
    - "FNO"
    - "RFS"
    - "JAC"

training_settings:
  num_train: 128
