base_config: ../ns_default.yaml

experiment:
  name: "n=128_e=8_m=FNO_s=RFS_l=JAC"
  tags:
    - "8 Eigenvectors"
    - "128 samples"
    - "FNO"
    - "RFS"
    - "JAC"

training_settings:
  num_samples: 128
