experiment:
  name: "NS_training"
  log_dir: "logs"
  output_dir: "output"
  checkpoint_dir: "checkpoints"
  model_type: "NS"
  dataset_type: "NS"
  seed: 42
  debug: false
  tags:
    - "NS"
    - "JAC"

data_settings:
  nx: 128
  ny: 128
  batch_size: 1
  eigen_count: 1
  sample_directories:
    - "/home/ubuntu/DeFINO/datasets/dataset_NS_batch1"
    - "/home/ubuntu/DeFINO/datasets/dataset_NS_batch2"

model_settings:
  in_channels: 1
  out_channels: 1
  decoder_layer_size: 128
  num_fno_layers: 6
  num_fno_modes: [32, 32]
  padding: 3
  dimension: 2
  latent_channels: 32
  loss_type: "L2"  # "L2" / "JAC"
  reg_param: 0.5 # not used for L2
  scale_factor: 5500.0 # not used for L2
  learning_rate: 1e-3
  weight_decay: 5e-4

training_settings:
  accum_steps: 1
  num_epoch: 2
  num_train: 2
  num_test: 2
  enable_checkpointing: true
  log_checkpoint: false # log to neptune (cloud)
  checkpoint_interval: 1
  save_top_k: 1

visualization_settings:
  save_to_disk: true
  log_to_neptune: false
  num_plots: 2
  check_val_every_n_epoch: 1
  plot_interval: 10

neptune:
  enabled: true
  project: "slim-gatech/DeFINO"
