base_config: ../ns_default.yaml

experiment:
  name: "n=128_e=5_m=FNO_s=RFS_l=JAC"
  tags:
    - "5 Eigenvectors"
    - "128 samples"
    - "FNO"
    - "RFS"
    - "JAC"

model_settings:
  train_eigen_count: 5
