base_config: ../ns_default.yaml

experiment:
  name: "n=64_e=8_m=FNO_s=RFS_l=JAC"
  tags:
    - "8 Eigenvectors"
    - "64 samples"
    - "FNO"
    - "RFS"
    - "JAC"

model_settings:
  train_eigen_count: 8
