experiment:
  name: "Navier Stokes Generation"
  seed: 42
  simulator_type: "NS"
  reduced_model_type: "RAND" # "FIM" or "RAND"

viz_settings:
  plot_interval: 1
  plot_vector_count: 1
  plots_dir: "datasets/dataset_NS/plots"

data_settings:
  num_samples: 2
  num_workers: 1
  output_dir: "datasets/dataset_NS/samples"

simulator_settings:
  s1: 128 # Grid size
  s2: 128 # Grid size
  scale: 10.0
  T: 1.0
  Re: 100
  adaptive: True
  delta_t: 1e-3
  nsteps: 25

reduced_model_settings:
  eigen_value_fraction: 0.01
  eigen_vector_count: 1 # Overrides eigen_value_fraction if set
