experiment:
  name: "Navier Stokes Generation"
  seed: 42
  simulator_type: "NS"
  reduced_model_type: "FIM"

viz_settings:
  plot_interval: 1
  plot_vector_count: 2
  plots_dir: "datasets/dataset_NS/plots"

data_settings:
  num_samples: 1
  output_dir: "datasets/dataset_NS/"

simulator_settings:
  N: 128 # Grid size
  L: 1.0 # Domain length
  dt: 0.001 # Time step
  nu: 0.001 # Viscosity
  nsteps: 1 # Number of time steps to forward solve

reduced_model_settings:
  eigen_value_fraction: 0.01
  eigen_vector_count: 2 # Overrides eigen_value_fraction if set
